apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: sweeper
  name: sweeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sweeper-controller
  namespace: sweeper
  labels:
    app: sweeper
spec:
  selector:
    matchLabels:
      app: sweeper
  replicas: 1
  template:
    metadata:
      labels:
        app: sweeper
    spec:
      serviceAccountName: sweeper
      containers:
      - command:
        - /manager
        image: controller:latest
        # imagePullPolicy: Never
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sweeper
  namespace: sweeper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sweeper
subjects:
- kind: ServiceAccount
  name: sweeper
  namespace: sweeper
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
