# permissions for end users to view kubernetes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-viewer-role
rules:
- apiGroups:
  - selector.sweeper.io
  resources:
  - kubernetes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - selector.sweeper.io
  resources:
  - kubernetes/status
  verbs:
  - get
