apiVersion: selector.sweeper.io/v1alpha1
kind: Kubernetes
metadata:
  name: kubernetes-sample
spec:
  groupVersionKinds: 
    - group: "apps"
      version: "v1"
      kind: "Deployment"
    - group: ""
      version: "v1"
      kind: "Service"
  objectLabels:
    "sweeper.io/enabled": "true"
  ttl: "1h"
